import Head from 'next/head';
import Image from 'next/image';
import cx from 'classnames';
import { useState, useEffect }  from 'react';
import styles from '../styles/Home.module.css';
import { v4 as uuidv4 } from "uuid";
import prisma from '../lib/prisma';
import { Router } from 'next/router';

export default function Home() {

  const [tasks, setTasks] = useState([]);
  const [task, setTask] = useState({task: ''});

  
  
  return (
    <div className={styles.container}>
      <Head>
        <title>TODO APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          TODO APP
        </h1>
        <div>
          <form>
            <input 
            type="text"
            placeholder='Add Task'
            value={task.task}/>
            <button type='submit' >
              {task.id? "Update": "Add"}
            </button>
          </form>
          {task.map((task) => (
            <div key={task.id}>
              <input
              type="checkbox"
              checked={task.completed}/>
              <P
              className={
                task.completed ?
                  styles.task.text + "" + styles.line_through
                  :styles.task.test
              }>{task.task}</P>
              <button>&#9998;</button>
              <button>&#10006</button>
            </div>
          ))}
          {tasks.length === 0 && <h2>No Tasks</h2>}
          
        </div>
      </main>

      <footer>
        
      </footer>
    </div>
  )
}
